[package]
name = "disle"
version = "0.4.2"
authors = ["Geobert Quach <geobert@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.22", features = ["macros", "sync", "signal"]}
caith = "0.5.0"
once_cell = "1.4.0"
ron = "0.6.0"
serde = { version = "1.0.114", features = ["serde_derive"] }
futures = "0.3.5"

[dependencies.serenity]
git = "https://github.com/acdenisSK/serenity"
rev = "8c8a172e7f19ed792440547c7ef99d15aadb3938"