[package]
name = "disle"
version = "0.6.0"
authors = ["Geobert Quach <geobert@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.22", features = ["macros", "sync", "signal", "rt-threaded"] }
caith = "2.0.0"
ron = "0.6.2"
serde = { version = "1.0.115", features = ["serde_derive"] }
futures = "0.3.5"
serenity = "0.9.0-rc.0"
