on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build_and_test:
    name: ${{ matrix.job.os }} (${{ matrix.job.target }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-latest , target: x86_64-unknown-linux-gnu }
          - { os: windows-2019 , target: x86_64-pc-windows-msvc }
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test --release && cargo build --release
      - name: Output dir 
        id: output_dir
        shell: bash
        run: |
          EXE_suffix=""
          case ${{ matrix.job.target }} in
            *-pc-windows-*) EXE_suffix=".exe" ;;
          esac;
          cp target/release/disle${EXE_suffix} .
          tar czf disle-${{ matrix.job.target }}.tgz disle${EXE_suffix}

          echo ::set-output name=BIN_NAME::disle-${{ matrix.job.target }}.tgz

      - name: Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ steps.output_dir.outputs.BIN_NAME }}
          allowUpdates: true
          
